# Generated by Django 3.2.5 on 2023-09-08 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0002_auto_20230908_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 16, 16, 22, 199358)),
        ),
    ]
