# Generated by Django 3.2.5 on 2023-09-08 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0003_alter_player_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
